name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ESLint
        run: |
          yarn install
          yarn lint
      - name: deploy to xxx
        run: |
